spring.application.name=chupinvet

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chupinvet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:chupinvet}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:chupinvet}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

spring.jackson.default-property-inclusion=non_null
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

springdoc.info.title=ChupinVet API 
springdoc.info.description=Documentacao da API ChupinVet - MySQL containerizado
springdoc.info.version=v1.0.0
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.try-it-out-enabled=true

server.port=${PORT:8080}

app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=${JWT_EXPIRATION_MS:3600000}